matrix:
  include:
    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'bc']
      env:
        ENV="GCC 4.8"
        COMPILER=g++-4.8
        FLAGS="-std=c++11 -O2 -Wall -Wextra -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/spec.sh

    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'bc']
      env:
        ENV="GCC 7"
        COMPILER=g++-7
        FLAGS="-std=c++17 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/spec.sh

    - os: linux
      language: cpp
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'llvm-toolchain-precise']
          packages: ['clang++-3.8', 'libc++-dev', 'bc']
      env:
        ENV="Clang 3.8"
        COMPILER=clang++-3.8
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/spec.sh

    - os: linux
      language: ocaml
      install:
        - sudo add-apt-repository --yes ppa:avsm/ppa
        - sudo apt-get update
        - sudo apt-get install opam
        - opam init -y
        - eval $(opam config env)
        - opam config var root
        - opam install -y num batteries
      env:
        ENV="OCaml"
        COMPILER=ocamlopt
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./ocaml/spec.sh

    - os: linux
      language: python
      python: '3.5'
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-format-3.9']
      env:
        ENV="Doxygen 1.8.13, ClangFormat"
      install:
        - wget https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz
        - tar xpvf Release_1_8_13.tar.gz
        - pushd doxygen-Release_1_8_13
        - cmake -DCMAKE_INSTALL_PREFIX=/usr .
        - sudo make install
        - popd
      script:
        - doxygen --version
        - python --version
        - ./build.sh
        - git diff --exit-code

    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        ENV="Preprocessor w/ GCC 6"
        COMPILER=g++-6
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/preprocess/test.sh

before_install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install git+https://github.com/asi1024/red-baron.git

sudo: required

notifications:
  email: false
