dist: xenial

matrix:
  include:
    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        ENV="GCC 4.8"
        CXX=g++-4.8
        CXXFLAGS="-std=c++11 -O2 -Wall -Wextra -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - ./cpp/spec.sh

    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        ENV="GCC 7"
        CXX=g++-7
        CXXFLAGS="-std=c++17 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - ./cpp/spec.sh

    - os: linux
      language: cpp
      compiler: clang++
      addons:
        apt:
          packages:
            - clang++-3.8
            - libc++-dev
      env:
        ENV="Clang 3.8"
        CXX=clang++-3.8
        CXXFLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
      script:
        - ulimit -s unlimited
        - ./cpp/spec.sh

    - os: linux
      language: ocaml
      install:
        - sudo add-apt-repository --yes ppa:avsm/ppa
        - sudo apt-get update
        - sudo apt-get install opam
        - opam init -y
        - eval $(opam config env)
        - opam config var root
        - opam install -y num batteries
      env:
        ENV="OCaml"
      script:
        - ulimit -s unlimited
        - ./ocaml/spec.sh

    - os: linux
      language: python
      python: '3.6'
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-format-3.9']
      env:
        ENV="Doxygen 1.8.13, ClangFormat"
      install:
        - wget https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz
        - tar xpvf Release_1_8_13.tar.gz
        - pushd doxygen-Release_1_8_13
        - cmake -DCMAKE_INSTALL_PREFIX=/usr .
        - sudo make install
        - popd
      script:
        - doxygen --version
        - python --version
        - ./build.sh
        - git diff --exit-code

    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        ENV="Preprocessor w/ GCC 6"
        COMPILER=g++-6
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/preprocess/test.sh

before_install:
  - pyenv versions
  - pyenv global 3.6
  - pip install --upgrade pip
  - pip install git+https://github.com/asi1024/red-baron.git

cache:
  - apt
  - pip
  - directories:
    - ~/.red-baron

sudo: required

notifications:
  email: false
