dist: xenial

matrix:
  include:
    - language: cpp
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILE="g++-7 -std=gnu++17 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - ./scripts/test.sh cpp

    - language: cpp
      compiler: clang++
      addons:
        apt:
          packages:
            - clang++-3.8
            - libc++-dev
      env:
        - COMPILE="clang++-3.8 -std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
      script:
        - ./scripts/test.sh cpp

    - language: python
      python: '3.7'
      addons:
        apt:
          packages:
            - 'clang-format-3.9'
      env:
        - ENV="Static check"
      script:
        - python --version
        - ./build.sh
        - git diff --exit-code

    - language: cpp
      compiler: g++
      env:
        - ENV="Example test"
      script:
        - pip install .
        - cd example
        - ./tutorial.sh

before_install:
  - pyenv versions
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install -U online-judge-tools
  - ulimit -s 1048576

cache:
  - apt
  - pip
  - directories:
    - ${HOME}/.workspace

sudo: required

notifications:
  email: false
