dist: xenial

matrix:
  include:
    - language: cpp
      compiler: g++
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - ENV="GCC 4.8"
        - PYTHON_VERSION="3.7"
      script:
        - export CXX=g++-4.8
        - export CXXFLAGS="-std=c++11 -O2 -Wall -Wextra -Wno-unused-result -Werror"
        - ulimit -s unlimited
        - red-baron cpp/src

    - language: cpp
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - ENV="GCC 7"
        - PYTHON_VERSION="3.7"
      script:
        - export CXX=g++-7
        - export CXXFLAGS="-std=c++17 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
        - ulimit -s unlimited
        - red-baron cpp/src

    - language: cpp
      compiler: clang++
      addons:
        apt:
          packages:
            - clang++-3.8
            - libc++-dev
      env:
        - ENV="Clang 3.8"
        - PYTHON_VERSION="3.7"
      script:
        - export CXX=clang++-3.8
        - export CXXFLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
        - ulimit -s unlimited
        - red-baron cpp/src

    - language: ocaml
      install:
        - sudo add-apt-repository --yes ppa:avsm/ppa
        - sudo apt-get update
        - sudo apt-get install opam
        - opam init -y
        - eval $(opam config env)
        - opam config var root
        - opam install -y num batteries
      env:
        - ENV="OCaml"
        - PYTHON_VERSION="3.6"
      script:
        - ulimit -s unlimited
        - red-baron ocaml/src

    - language: python
      python: '3.7'
      addons:
        apt:
          packages:
            - 'clang-format-3.9'
      env:
        - ENV="Doxygen 1.8.15, ClangFormat"
        - PYTHON_VERSION="3.7"
      install:
        - wget https://github.com/doxygen/doxygen/archive/Release_1_8_15.tar.gz
        - tar xpvf Release_1_8_15.tar.gz
        - pushd doxygen-Release_1_8_15
        - cmake -DCMAKE_INSTALL_PREFIX=/usr .
        - sudo make install
        - popd
      script:
        - doxygen --version
        - python --version
        - ./build.sh
        - git diff --exit-code

before_install:
  - pyenv versions
  - pyenv global ${PYTHON_VERSION}
  - pip install --upgrade pip
  - pip install git+https://github.com/asi1024/red-baron.git

cache:
  - apt
  - pip
  - directories:
    - ${HOME}/.red_baron

sudo: required

notifications:
  email: false
