dist: xenial

matrix:
  include:
    - language: cpp
      compiler: g++
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - ENV="GCC 4.8"
        - COMPILE="g++-4.8 -std=gnu++11 -O2 -Wall -Wextra -Wno-unused-result -Werror"
        - PYTHON_VERSION="3.7"
      script:
        - ulimit -s unlimited
        - ./scripts/test.sh cpp

    - language: cpp
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - ENV="GCC 7"
        - COMPILE="g++-7 -std=gnu++17 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
        - PYTHON_VERSION="3.7"
      script:
        - ulimit -s unlimited
        - ./scripts/test.sh cpp

    - language: cpp
      compiler: clang++
      addons:
        apt:
          packages:
            - clang++-3.8
            - libc++-dev
      env:
        - ENV="Clang 3.8"
        - COMPILE="clang++-3.8 -std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
        - PYTHON_VERSION="3.7"
      script:
        - ulimit -s unlimited
        - ./scripts/test.sh cpp

    - language: python
      python: '3.7'
      addons:
        apt:
          packages:
            - 'clang-format-3.9'
      env:
        - ENV="Doxygen 1.8.15, ClangFormat"
        - PYTHON_VERSION="3.7"
      script:
        - python --version
        - ./build.sh
        - git diff --exit-code

    - language: cpp
      compiler: g++
      script:
        - cd example
        - ./tutorial.sh

before_install:
  - pyenv versions
  - pyenv global ${PYTHON_VERSION}
  - pip install --upgrade pip
  - pip install online-judge-tools

cache:
  - apt
  - pip
  - directories:
    - ${HOME}/.workspace

sudo: required

notifications:
  email: false
