language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'bc']
      env:
        COMPILER=g++-5
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Werror"
        GCOV=gcov-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        COMPILER=g++-6
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Werror"
        GCOV=gcov-6

sudo: false

script:
  - ulimit -s unlimited
  - ulimit -a
  - $COMPILER --version
  - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/spec.sh --all
notifications:
  email: false
