matrix:
  include:
    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'bc']
      env:
        DIR="cpp"
        COMPILER=g++-5
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./${DIR}/spec.sh --all

    - os: linux
      language: cpp
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        DIR="cpp"
        COMPILER=g++-6
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./${DIR}/spec.sh --all

    - os: linux
      language: cpp
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'llvm-toolchain-precise']
          packages: ['clang++-3.8', 'libc++-dev', 'bc']
      env:
        DIR="cpp"
        COMPILER=clang++-3.8
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror -stdlib=libc++"
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./${DIR}/spec.sh --all

    - os: linux
      language: ocaml
      install:
        - sudo add-apt-repository --yes ppa:avsm/ppa
        - sudo apt-get update
        - sudo apt-get install opam
        - opam init -y
        - eval $(opam config env)
        - opam config var root
        - opam install -y num batteries
      env:
        DIR="ocaml"
        COMPILER=ocamlopt
      script:
        - ulimit -s unlimited
        - CXX=$COMPILER CXXFLAGS=$FLAGS ./${DIR}/spec.sh --all

    - os: linux
      language: python
      script:
        - cp -r docs docs-spec
        - rm -rf docs/cpp
        - python --version
        - ./gendoc.sh
        - diff -r docs docs-spec

sudo: required


notifications:
  email: false
