language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        CXX=g++-5
        CXXFLAGS="--std=c++14 -Wall -Wextra -Werror"
        GCOV=gcov-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        CXX=g++-6
        CXXFLAGS="--std=c++14 -Wall -Wextra -Werror"
        GCOV=gcov-6

sudo: false

%% before_install:
%%   - pip install --user cpp-coveralls
script:
  - $CXX --version
  - ./specs
  %% - coveralls --gcov $GCOV --gcov-options '\-lp'
  %% - $COMPILER -std=c++14 -O0 benchmarks/main.cpp -Wall -o exec
  %% - ./exec
notifications:
  email: false
