language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'bc']
      env:
        COMPILER=g++-5
        CXXFLAGS="-std=c++14 -Wall -Wextra -Werror"
        GCOV=gcov-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        COMPILER=g++-6
        CXXFLAGS="-std=c++14 -Wall -Wextra -Werror"
        GCOV=gcov-6

sudo: false

script:
  - $COMPILER --version
  - CXX=$COMPILER ./cpp/spec.sh
notifications:
  email: false
